#
# Module manifest for module 'module'
#
# Generated by: pwujczyk
#
# Generated on: 4/27/2021 1.0.01:54 PM
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ProductivityTools.PublishReadmeToWordpress.psm1'

# Version number of this module.
ModuleVersion = '0.0.5'

# ID used to uniquely identify this module
GUID = 'ce102c7c-c62e-4373-bb61-b386562007ae'

# Author of this module
Author = 'Pawel Wujczyk'

# Description of the functionality provided by this module
Description = 'It publishes Readme file to the wordpress'

# Functions to export from this module
FunctionsToExport = 'Publish-ReadmeToBlog'

# List of all files packaged with this module
FileList = @('./ProductivityTools.PublishToWordpress.psm1')

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

